[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'

[tool.mypy]
# incremental = true

follow_imports = 'skip'
ignore_missing_imports = true
show_error_codes = true

# disallow_any_unimported = true
# disallow_any_expr = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

no_implicit_optional = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_no_return = true
warn_unreachable = true

show_none_errors = true

[tool.autoflake]
remove_all_unused_imports = true
ignore_init_module_imports = true
